name: Comment test
on:
  push:
  workflow_dispatch:
jobs:
  randomized_tests:
    name: Comment test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create comment on failed test run
        #if: ${{ failure() }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: 17
          body: |
            Randomized tests check:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
