name: Issues report generation

on:
  push:
  schedule:
    - cron:  '5 8 * * 2' # each Tuesday at 8 05
  workflow_dispatch:

jobs:
  generate_issue_report:
    runs-on: ubuntu-latest
    steps:

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%m-%d-%Y:%H:%M')"
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Checkout base code
        uses: actions/checkout@v2
      - name: Checkout wiki code
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: reports

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Generate report
        run: |
          python manager.py --token="${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}" generate_reports_to_folder '["https://github.com/Qiskit/qiskit-terra","https://github.com/Qiskit/qiskit-tutorials"]'
      - name: Push to wiki
        run: |
          cd reports
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "Issue report for ${{ steps.date.outputs.date }}" && git push
      - name: Remove reports folder
        run: rm -r reports
      - name: Commit saved issues metadata and create Pull Request
        if: ${{ success() }}
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Generated report metadata ${{ steps.date.outputs.date }}.
          title: Generated report metadata ${{ steps.date.outputs.date }}.
          body: Generated report metadata ${{ steps.date.outputs.date }}.
          branch: auto-report-metadata-${{ steps.date.outputs.date }}
          base: main